
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/ThemeProvider";
import Header from "./(root)/website/Header";
import { SidebarProvider } from "@/components/ui/sidebar";
import WebsitSideBar from "@/components/Application/websit/WebsitSideBar";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true} 
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="Light"
            enableSystem={false}
            disableTransitionOnChange
          >
              <Header/>
              <SidebarProvider >
              <WebsitSideBar/> 
              
          {children}
          </SidebarProvider>
          </ThemeProvider>
        
      </body>
    </html>
  );
}
